
spring:
    datasource:
        url: jdbc:mysql://47.95.197.99:3306/pig_eat?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        driverClassName: com.mysql.jdbc.Driver
        hikari:
            minimum-idle: 5
            maximum-pool-size: 15
            auto-commit: true
            idle-timeout: 30000
            max-lifetime: 1800000
            connection-timeout: 10000
            connection-test-query: SELECT 1