server:
    port:8080

mybatis:
    mapper-locations: classpath*:mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
    type-aliases-package: com.pighome.eat.dataobject

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: false
    supportMethodsArguments: true
    params: count=countSql


spring:
    profiles:
        active: dev